// Generated by scripts/domain-packages.mjs. Do not edit.
import type { DomainRuntimeMcpServerLauncher } from '@sciforge/domain-sdk/node/runtime-mcp-launcher'
import { selectedDomainRuntimeMcpContributionId } from '@sciforge/domain-sdk/node/runtime-mcp-launcher'
import { runDomainRuntimeMcpServerFromArgv as runDomainRuntimeMcpServer0 } from '@sciforge/domain-computer-use/runtime-mcp'

const installedDomainRuntimeMcpServerLaunchers: Readonly<Record<string, DomainRuntimeMcpServerLauncher>> = Object.freeze({
  "computer-use.runtime-mcp-server": runDomainRuntimeMcpServer0
})

export async function runInstalledDomainRuntimeMcpServerFromArgv(
  argv: string[]
): Promise<boolean> {
  const contributionId = selectedDomainRuntimeMcpContributionId(argv)
  if (contributionId === null) return false
  const launcher = installedDomainRuntimeMcpServerLaunchers[contributionId]
  if (!launcher) {
    throw new Error(`Installed domain runtime MCP contribution is unavailable: ${contributionId}`)
  }
  await launcher(argv)
  return true
}
